### ISSUE TITLE
Server crashes when hg repo is locked

### ISSUE THREAD

**Issue by lbergnehr** [lbergnehr/hg_log#4]
W20141230-10:20:30.216(1)? (STDERR)
    W20141230-10:20:30.224(1)? (STDERR) [repo path]/hg_log/.meteor/local/isopacks/npm-container/npm/node_modules/Rx/dist/rx.all.js:9060
    W20141230-10:20:30.267(1)? (STDERR)                 throw e;
    W20141230-10:20:30.268(1)? (STDERR)                       ^
    W20141230-10:20:31.307(1)? (STDERR) Error: waiting for lock on repository /tmp/repos/test held by '[host holding lock]'
    W20141230-10:20:31.308(1)? (STDERR)
    W20141230-10:20:31.308(1)? (STDERR)   at HGCommandServer._handleServerData ([repo path]/hg_log/.meteor/local/isopacks/npm-container/npm/node_modules/hg/lib/HGCommandServer.coffee:167:32)
    W20141230-10:20:31.309(1)? (STDERR)   at Socket.bound ([repo path]/hg_log/.meteor/local/isopacks/npm-container/npm/node_modules/hg/node_modules/lodash/dist/lodash.js:729:21)
    W20141230-10:20:31.310(1)? (STDERR)   at Socket.emit (events.js:95:17)
    W20141230-10:20:31.311(1)? (STDERR)   at Socket.<anonymous> (_stream_readable.js:764:14)
    W20141230-10:20:31.311(1)? (STDERR)   at Socket.emit (events.js:92:17)
    W20141230-10:20:31.312(1)? (STDERR)   at emitReadable_ (_stream_readable.js:426:10)
    W20141230-10:20:31.315(1)? (STDERR)   at emitReadable (_stream_readable.js:422:5)
    W20141230-10:20:31.317(1)? (STDERR)   at readableAddChunk (_stream_readable.js:165:9)
    W20141230-10:20:31.318(1)? (STDERR)   at Socket.Readable.push (_stream_readable.js:127:10)
    W20141230-10:20:31.319(1)? (STDERR)   at Pipe.onread (net.js:528:21)
    W20141230-10:20:31.320(1)? (STDERR)
    => Exited with code: 8

**Comment by lbergnehr** [comment]
This was resolved in #12.
